[package]
name = "megaminer2025"
version = "0.1.0"
edition = "2024"

[dependencies]
jsonschema = "0.30.0"
schemars = "0.8.22"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
strum = "0.27.1"
strum_macros = "0.27.1"
